package com.hcl;

import static org.junit.jupiter.api.Assertions.*;

import org.junit.jupiter.api.Test;

class AbcabaPatternTest {

	@Test
	public void test1() {
		assertEquals("A", AbacabaPattern.abacabaPattern(1));
	}

	@Test
	public void test2() {
		assertEquals("ABA", AbacabaPattern.abacabaPattern(2));
	}

	@Test
	public void test3() {
		assertEquals("ABACABA", AbacabaPattern.abacabaPattern(3));
	}

	@Test
	public void test4() {
		assertEquals("ABACABADABACABA", AbacabaPattern.abacabaPattern(4));
	}

	@Test
	public void test5() {
		assertEquals("ABACABADABACABAEABACABADABACABA", AbacabaPattern.abacabaPattern(5));
	}

	@Test
	public void test6() {
		assertEquals("ABACABADABACABAEABACABADABACABAFABACABADABACABAEABACABADABACABA",
				AbacabaPattern.abacabaPattern(6));
	}

	@Test
	public void test7() {
		assertEquals(
				"ABACABADABACABAEABACABADABACABAFABACABADABACABAEABACABADABACABAGABACABADABACABAEABACABADABACABAFABACABADABACABAEABACABADABACABA",
				AbacabaPattern.abacabaPattern(7));
	}

	@Test
	public void test8() {
		assertEquals(
				"ABACABADABACABAEABACABADABACABAFABACABADABACABAEABACABADABACABAGABACABADABACABAEABACABADABACABAFABACABADABACABAEABACABADABACABAHABACABADABACABAEABACABADABACABAFABACABADABACABAEABACABADABACABAGABACABADABACABAEABACABADABACABAFABACABADABACABAEABACABADABACABA",
				AbacabaPattern.abacabaPattern(8));
	}

	@Test
	public void test9() {
		assertEquals(
				"ABACABADABACABAEABACABADABACABAFABACABADABACABAEABACABADABACABAGABACABADABACABAEABACABADABACABAFABACABADABACABAEABACABADABACABAHABACABADABACABAEABACABADABACABAFABACABADABACABAEABACABADABACABAGABACABADABACABAEABACABADABACABAFABACABADABACABAEABACABADABACABAIABACABADABACABAEABACABADABACABAFABACABADABACABAEABACABADABACABAGABACABADABACABAEABACABADABACABAFABACABADABACABAEABACABADABACABAHABACABADABACABAEABACABADABACABAFABACABADABACABAEABACABADABACABAGABACABADABACABAEABACABADABACABAFABACABADABACABAEABACABADABACABA",
				AbacabaPattern.abacabaPattern(9));
	}
	
	@Test
	public void test10NegativeTestLeaveOffFirstCharTest9() {
		assertNotEquals(
				"BACABADABACABAEABACABADABACABAFABACABADABACABAEABACABADABACABAGABACABADABACABAEABACABADABACABAFABACABADABACABAEABACABADABACABAHABACABADABACABAEABACABADABACABAFABACABADABACABAEABACABADABACABAGABACABADABACABAEABACABADABACABAFABACABADABACABAEABACABADABACABAIABACABADABACABAEABACABADABACABAFABACABADABACABAEABACABADABACABAGABACABADABACABAEABACABADABACABAFABACABADABACABAEABACABADABACABAHABACABADABACABAEABACABADABACABAFABACABADABACABAEABACABADABACABAGABACABADABACABAEABACABADABACABAFABACABADABACABAEABACABADABACABA",
				AbacabaPattern.abacabaPattern(9));
	}
	
	
	

}
